spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 712620782396-b3tl0q7psgodfbj41e720m5gc3e090ao.apps.googleusercontent.com
            client-secret: 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
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
            redirect-uri: http://ec2-3-39-2-87.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
          naver:
            client-name: naver
            client-id: KZgZON8q7InN50LVfi5l
            client-secret: pypfRcLCe9
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: http://ec2-3-39-2-87.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
          kakao:
            client-name: kakao
            client-id: d227d38f6839c549cdeadda37eeaa977
            client-secret: ge72tYUvgdGMvlEh4zJwYFaGrlNF8SsX
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: http://ec2-3-39-2-87.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/maimu
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://maimu-db.cr64ekoo6d22.ap-northeast-2.rds.amazonaws.com:3306/maimu-db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: a123456789

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessExpiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG

